### ISSUE TITLE
Doesn't work....

### ISSUE THREAD

**Issue by matchr89** [m42cel/Google-Maps-Anti-DMA#1]
It's not does not a thing. Very sad. 5 of 7 stars. Wouldn't recommend.

**Comment by m42cel** [comment]
First of all, thanks for the perfect score.

It should be working currently. If you're on Chrome please check if Tampermonkey still asks you to enable developer mode:
<img width="1003" alt="grafik" src="https://github.com/user-attachments/assets/81c1cf56-bf1a-4869-b72e-790f8e60496a">

To do so, go to `chrome://extensions` and enable the Developer Mode in the top right corner:

![grafik](https://github.com/user-attachments/assets/ab9ad6f1-981a-416d-a3dd-93386ddd4acc)

For more information, see: https://www.tampermonkey.net/faq.php#Q209
